### ISSUE TITLE
get文章列表时出现no session

### ISSUE THREAD

**Issue by Lamken** [Sunshiqisky/wechat_crawler#1]
谢谢您的分享，采用您的代码之后，更新了fiddler上的header以及get请求上的appmsg_token和pass_ticket
但是服务器返回的信息是 b'{"base_resp":{"ret":-3,"errmsg":"no session","cookie_count":0},"ret":-3,"errmsg":"no session","cookie_count":0}'期待您的帮助

很抱歉打扰到您，测试之后发现是我修改了您的header_to_dict函数，导致发送的header不正确

**Comment by Sunshiqisky** [comment]
不好意思，今天才看到

**Comment by Sunshiqisky** [comment]
问题解决了吗？看着像是抓评论信息的时候get请求的url或者headers有问题

**Comment by Lamken** [comment]
谢谢您的关心，问题暂时用不良好的方法解决了。
问题在于，每个公众号的appmsg_token在关注前后是不一样的。
解决方法是关注之后再重新抓包。否则就会出现response返回no session不返回推送内容的情况。

**Comment by fansity** [comment]
新手想请问一下，我目前是在抓取微信公众号文章的评论，但是get请求评论页接口后也显示"ret":-3,"errmsg":"no session",看您上面说可能是header有问题，那么我想请教一下您这个Header里这么多的参数从哪里来？我从fiddler中得到的好像并没有您这么多？

**Comment by Sunshiqisky** [comment]
@fansity  你可以试下Lamken的方法，关注之后再重新抓包。
